// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBk7pu7vIantVYCM9Y_4YPAe3Dazmc77A',
    appId: '1:144128552152:web:59ea2bbbc093f0d4c1fbad',
    messagingSenderId: '144128552152',
    projectId: 'studenttracker-410014',
    authDomain: 'studenttracker-410014.firebaseapp.com',
    storageBucket: 'studenttracker-410014.appspot.com',
    measurementId: 'G-0DS79WP9BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqeirjJNG3I-BxvNjTK85x78GNMY3gKQ',
    appId: '1:144128552152:android:de3644db918363b8c1fbad',
    messagingSenderId: '144128552152',
    projectId: 'studenttracker-410014',
    storageBucket: 'studenttracker-410014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUML9-CBMLHuSdNHctCw48TBCWBLbbns0',
    appId: '1:144128552152:ios:de42624c87742583c1fbad',
    messagingSenderId: '144128552152',
    projectId: 'studenttracker-410014',
    storageBucket: 'studenttracker-410014.appspot.com',
    iosBundleId: 'com.nm.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUML9-CBMLHuSdNHctCw48TBCWBLbbns0',
    appId: '1:144128552152:ios:6c86e3b75edcb7e3c1fbad',
    messagingSenderId: '144128552152',
    projectId: 'studenttracker-410014',
    storageBucket: 'studenttracker-410014.appspot.com',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBk7pu7vIantVYCM9Y_4YPAe3Dazmc77A',
    appId: '1:144128552152:web:cb15c96118a6bdc4c1fbad',
    messagingSenderId: '144128552152',
    projectId: 'studenttracker-410014',
    authDomain: 'studenttracker-410014.firebaseapp.com',
    storageBucket: 'studenttracker-410014.appspot.com',
    measurementId: 'G-VXLXB56MR1',
  );
}
